<?php

$tourAuthUser = auth()->user();
$tourSteps = collect([
    [
        'key' => 'products',
        'title' => 'Create catalog items',
        'section' => 'Control Setup',
        'purpose' => 'Every downstream workflow depends on valid catalog items, SKUs, and pricing setup.',
        'action' => 'Before adding a catalog item, set up Packaging Types and Tax / VAT Classes. Then create the SKU with its name, price, packaging, and tax linkage.',
        'path' => route('admin.products.index'),
        'selector' => '[data-tour="products-primary-action"]',
        'permission' => 'control.products',
    ],
    [
        'key' => 'products-form',
        'title' => 'Fill the product form',
        'section' => 'Control Setup',
        'purpose' => 'A usable catalog record needs more than just a name. Orders, operations, VAT, and packaging all read from this setup.',
        'action' => 'If Packaging Types and Tax / VAT Classes are already created, fill Product Name, SKU, base price, packaging type, and tax class first. Then add size, volume, image, and description.',
        'path' => route('admin.products.create'),
        'selector' => '[data-tour="product-form-basics"]',
        'spotlight' => false,
        'permission' => 'control.products',
    ],
    [
        'key' => 'products-save',
        'title' => 'Save and publish the SKU',
        'section' => 'Control Setup',
        'purpose' => 'Saving the item makes it available to pricing, stock, and order workflows.',
        'action' => 'After checking the required fields and keeping the SKU active, use Save Product to add it to the catalog.',
        'path' => route('admin.products.create'),
        'selector' => '[data-tour="product-form-submit"]',
        'permission' => 'control.products',
    ],
    [
        'key' => 'agents',
        'title' => 'Register clients',
        'section' => 'Control Setup',
        'purpose' => 'Orders, credit checks, pricing, and commissions all depend on the client master.',
        'action' => 'Create client accounts, then maintain their price lists, credit terms, and commission rules.',
        'path' => route('admin.agents.index'),
        'selector' => '[data-tour="agents-primary-action"]',
        'permission' => 'control.agents',
    ],
    [
        'key' => 'suppliers',
        'title' => 'Maintain suppliers',
        'section' => 'Control Setup',
        'purpose' => 'Procurement starts from the supplier master.',
        'action' => 'Add supplier contacts, then use them when raising purchase orders and purchase bills.',
        'path' => route('admin.suppliers.index'),
        'selector' => '[data-tour="suppliers-primary-action"]',
        'permission' => 'control.suppliers',
    ],
    [
        'key' => 'warehouses',
        'title' => 'Set up warehouses',
        'section' => 'Control Setup',
        'purpose' => 'Stock visibility depends on warehouse structure and locations.',
        'action' => 'Create warehouses, depots, and storage locations before posting receipts, transfers, or deliveries.',
        'path' => route('admin.warehouses.index'),
        'selector' => '[data-tour="warehouses-primary-action"]',
        'permission' => 'control.warehouses',
    ],
    [
        'key' => 'purchase-orders',
        'title' => 'Raise purchase orders',
        'section' => 'Procurement',
        'purpose' => 'This starts the inbound material cycle from supplier to inventory.',
        'action' => 'Create and approve purchase orders for raw materials and packaging items that need replenishment.',
        'path' => route('admin.purchase-orders.index'),
        'selector' => '[data-tour="purchase-orders-primary-action"]',
        'permission' => 'control.suppliers',
    ],
    [
        'key' => 'goods-receipts',
        'title' => 'Post goods receipts',
        'section' => 'Procurement',
        'purpose' => 'GRN posting moves received material into stock and links it to procurement.',
        'action' => 'Receive supplier deliveries, record quantities, and confirm which stock entered the warehouse.',
        'path' => route('admin.goods-receipts.index'),
        'selector' => '[data-tour="goods-receipts-primary-action"]',
        'permission' => 'inventory.manage',
    ],
    [
        'key' => 'inventory',
        'title' => 'Review operations position',
        'section' => 'Operations',
        'purpose' => 'This shows what is available, reserved, and ready for fulfilment.',
        'action' => 'Use the operations views to check stock health before promising deliveries or dispatching new orders.',
        'path' => route('admin.inventory.index'),
        'selector' => '[data-tour="inventory-overview-header"]',
        'permission' => 'inventory.manage',
    ],
    [
        'key' => 'orders',
        'title' => 'Capture client orders',
        'section' => 'Orders',
        'purpose' => 'Client orders are the trigger for reservation, delivery, invoicing, and commissions.',
        'action' => 'Enter orders, apply pricing, validate credit, and move demand into warehouse fulfilment.',
        'path' => route('admin.orders.index'),
        'selector' => '[data-tour="orders-primary-action"]',
        'permission' => 'sales.manage',
    ],
    [
        'key' => 'finance',
        'title' => 'Issue client invoices',
        'section' => 'Finance',
        'purpose' => 'Delivered quantities become invoices, VAT, and receivable entries here.',
        'action' => 'Review invoices, receipts, credit notes, and outstanding balances after delivery is confirmed.',
        'path' => route('admin.finance.index'),
        'selector' => '[data-tour="finance-overview-header"]',
        'permission' => 'accounting.manage',
    ],
    [
        'key' => 'reconciliation',
        'title' => 'Reconcile collections',
        'section' => 'Finance',
        'purpose' => 'Cash collection is not complete until receipts are reconciled.',
        'action' => 'Use bank reconciliation to confirm collected receipts against the current finance period.',
        'path' => route('admin.finance.reconciliation'),
        'selector' => '[data-tour="reconciliation-overview-header"]',
        'permission' => 'accounting.manage',
    ],
    [
        'key' => 'reports',
        'title' => 'Close the cycle with reports',
        'section' => 'Reporting',
        'purpose' => 'Reports convert operations into management and financial truth.',
        'action' => 'Use the reports dashboard to review orders, finance, tax, and operational summaries after transactions are complete.',
        'path' => route('admin.reports.dashboard'),
        'selector' => '[data-tour="reports-drilldown"]',
        'permission' => 'reports.view',
    ],
    [
        'key' => 'settings',
        'title' => 'Finish with system settings',
        'section' => 'System',
        'purpose' => 'Branding, mail, SMS, and backups keep the ERP production-ready.',
        'action' => 'Configure logo, colors, currency, SMTP, SMS, and backup controls for daily use.',
        'path' => route('admin.settings.index'),
        'selector' => '[data-tour="settings-brand-identity"]',
        'permission' => 'system.settings',
    ],
])->filter(function ($step) use ($tourAuthUser) {
    if (!empty($step['path']) && \App\Helpers\MenuHelper::isAdminPathHidden($step['path'])) {
        return false;
    }

    return empty($step['permission']) || \App\Helpers\Permission::can($tourAuthUser, $step['permission']);
})->map(function ($step) {
    unset($step['permission']);
    return $step;
})->values()->all();
